In [1]:
import numpy as np


In [2]:
a = np.random.rand((480,480,3))

TypeError: 'tuple' object cannot be interpreted as an index

In [3]:
a = np.random.rand(480,480,3)

In [4]:
a


array([[[ 0.55422257,  0.95060163,  0.99904909],
        [ 0.57423534,  0.07562754,  0.92202168],
        [ 0.53476659,  0.58635158,  0.89648997],
        ..., 
        [ 0.55211111,  0.83369439,  0.257422  ],
        [ 0.64176182,  0.51771589,  0.23138084],
        [ 0.33459694,  0.85726956,  0.98910938]],

       [[ 0.48233023,  0.91074841,  0.94369987],
        [ 0.25442407,  0.29808365,  0.39233195],
        [ 0.22206726,  0.49044521,  0.710992  ],
        ..., 
        [ 0.08439663,  0.90736467,  0.44804182],
        [ 0.87776233,  0.23931648,  0.45738898],
        [ 0.09715008,  0.80487101,  0.02234519]],

       [[ 0.97845783,  0.18896594,  0.80719022],
        [ 0.33935506,  0.32527499,  0.45374314],
        [ 0.37729334,  0.2554575 ,  0.24808985],
        ..., 
        [ 0.25433413,  0.79644024,  0.22728086],
        [ 0.41641942,  0.46446666,  0.34173737],
        [ 0.01060592,  0.84649586,  0.84907449]],

       ..., 
       [[ 0.50116171,  0.59752351,  0.76524333],
        

In [5]:
b = np.empty([480,480,3])



In [6]:
b = np.concatenate((b,a),axis=0)

In [7]:
b

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        ..., 
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        ..., 
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        ..., 
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       ..., 
       [[ 0.50116171,  0.59752351,  0.76524333],
        

In [8]:
b.shape


(960, 480, 3)

In [9]:
c = np.empty((480,480,3))

In [10]:
c


array([[[  4.04738577e-320,   3.00391913e-321,   0.00000000e+000],
        [  1.87414119e-316,   4.94065646e-324,   1.87416807e-316],
        [  4.94065646e-324,   1.87414277e-316,   6.79038653e-313],
        ..., 
        [  6.79038653e-313,   9.33678148e-313,   2.33419537e-312],
        [  6.79038653e-313,   6.79038653e-313,   6.79038653e-313],
        [  6.79038653e-313,   6.79038654e-313,   9.76118064e-313]],

       [[  6.79038653e-313,   6.79038653e-313,   6.79038653e-313],
        [  6.79038653e-313,   6.79038653e-313,   1.01855798e-312],
        [  6.79038653e-313,   6.79038653e-313,   6.79038653e-313],
        ..., 
        [  4.54052257e-317,   6.91263672e-310,   4.94065646e-324],
        [  4.54050281e-317,   6.91263672e-310,   4.94065646e-324],
        [  4.54048305e-317,   6.91263672e-310,   4.94065646e-324]],

       [[  4.54046329e-317,   6.91263672e-310,   4.94065646e-324],
        [  4.54042376e-317,   6.91263672e-310,   9.88131292e-324],
        [  4.54040400e-317,   